FROM ruby:3.4.8

ENV LANG C.UTF-8
ENV TZ Asia/Tokyo

RUN apt-get update -qq \
  && apt-get install -y build-essential libpq-dev nodejs curl gnupg vim

RUN mkdir /myapp
WORKDIR /myapp

RUN gem install bundler

COPY . /myapp
